# Docker Compose script to run all three microservices locally.
# Use of this script:
#   docker compose -f docker/docker-compose.yml up
#   docker compose -f docker/docker-compose.yml down   (in a second terminal window)
#   Set specific environment variables:
#   export CAIG_GRAPH_SOURCE_TYPE="cosmos_vcore" ; docker compose -f docker-compose.yml up

services:

  web_app:
    image: cjoakim/caig_web:latest
    ports:
      - "8000:8000"
    volumes:
      - ./tmp:/tmp:rw
    environment:
      CAIG_GRAPH_SERVICE_PORT:           $CAIG_GRAPH_SERVICE_PORT
      CAIG_GRAPH_SERVICE_URL:            http://graph_service
      CAIG_AZURE_OPENAI_COMPLETIONS_DEP: $CAIG_AZURE_OPENAI_COMPLETIONS_DEP
      CAIG_AZURE_OPENAI_EMBEDDINGS_DEP:  $CAIG_AZURE_OPENAI_EMBEDDINGS_DEP
      CAIG_AZURE_OPENAI_KEY:             $CAIG_AZURE_OPENAI_KEY
      CAIG_AZURE_OPENAI_URL:             $CAIG_AZURE_OPENAI_URL
      CAIG_AZURE_MONGO_VCORE_CONN_STR:   $CAIG_AZURE_MONGO_VCORE_CONN_STR
      CAIG_GRAPH_SOURCE_DB:              $CAIG_GRAPH_SOURCE_DB
      CAIG_GRAPH_SOURCE_CONTAINER:       $CAIG_GRAPH_SOURCE_CONTAINER
      CAIG_CONVERSATIONS_CONTAINER:      $CAIG_CONVERSATIONS_CONTAINER
      CAIG_DOCUMENTS_CONTAINER:          $CAIG_DOCUMENTS_CONTAINER
      CAIG_DEFINED_AUTH_USERS:           $CAIG_DEFINED_AUTH_USERS
      CAIG_LOG_LEVEL:                    debug
      PORT:                              8000
      WEB_CONCURRENCY:                   1

  graph_service:
    image: cjoakim/caig_graph:latest
    ports:
      - "8001:8001"
    volumes:
      - ./tmp:/tmp:rw
    environment:
      CAIG_GRAPH_SOURCE_TYPE:            cosmos_vcore
      CAIG_AZURE_MONGO_VCORE_CONN_STR:   $CAIG_AZURE_MONGO_VCORE_CONN_STR
      CAIG_GRAPH_SOURCE_DB:              $CAIG_GRAPH_SOURCE_DB
      CAIG_GRAPH_SOURCE_CONTAINER:       $CAIG_GRAPH_SOURCE_CONTAINER
      CAIG_CONVERSATIONS_CONTAINER:      $CAIG_CONVERSATIONS_CONTAINER
      CAIG_DOCUMENTS_CONTAINER:          $CAIG_DOCUMENTS_CONTAINER
      CAIG_GRAPH_SOURCE_OWL_FILENAME:    $CAIG_GRAPH_SOURCE_OWL_FILENAME
      CAIG_GRAPH_SOURCE_RDF_FILENAME:    $CAIG_GRAPH_SOURCE_RDF_FILENAME
      CAIG_DEFINED_AUTH_USERS:           $CAIG_DEFINED_AUTH_USERS
      CAIG_LOG_LEVEL:                    debug
      PORT:                              8001
      WEB_CONCURRENCY:                   1


# WEB_CONCURRENCY relates to uvicorn and the --workers count; see https://www.uvicorn.org

# Use of this script:
# docker compose -f docker/docker-compose.yml up
# docker compose -f docker/docker-compose.yml down   (in a second terminal window)
