FROM    python:3.11-alpine
WORKDIR /app
RUN     mkdir -p /app/tmp
RUN     mkdir -p /app/uploads
RUN     apk add gcc python3-dev
RUN     apk add gcc musl-dev linux-headers python3-dev
COPY    . .
RUN     pip install --upgrade pip
RUN     pip install -r requirements-alpine.txt
RUN     pip list
EXPOSE  8000
CMD     ["uvicorn", "webapp:app", "--host", "0.0.0.0", "--port", "8000"]


# This file contains the instructions for building the Docker image.
# Chris Joakim, Microsoft
#
# Developer Notes:
# docker build -t cjoakim/caig_web .
# docker image ls
# docker ps
# docker stop -t 2 008038664a58
#
# DockerHub:
# docker push cjoakim/caig_web:latest
