# PowerShell script to set the necessary CAIG_ environment variables,
# generated by main.py on Mon Apr  1 16:22:20 2024
# Edit ALL of these generated values per your actual deployment.

echo "Setting CAIG environment variables"

echo 'setting CAIG_ACA_ENVIRONMENT_NAME'
[Environment]::SetEnvironmentVariable("CAIG_ACA_ENVIRONMENT_NAME", "caig", "User")

echo 'setting CAIG_AZURE_MONGO_VCORE_CONN_STR'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_MONGO_VCORE_CONN_STR", "mongodb+srv://...", "User")

echo 'setting CAIG_AZURE_OPENAI_COMPLETIONS_DEP'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_COMPLETIONS_DEP", "gpt4", "User")

echo 'setting CAIG_AZURE_OPENAI_EMBEDDINGS_DEP'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_EMBEDDINGS_DEP", "embeddings", "User")

echo 'setting CAIG_AZURE_OPENAI_KEY'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_KEY", "", "User")

echo 'setting CAIG_AZURE_OPENAI_URL'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_OPENAI_URL", "", "User")

echo 'setting CAIG_AZURE_REGION'
[Environment]::SetEnvironmentVariable("CAIG_AZURE_REGION", "eastus", "User")

echo 'setting CAIG_CONVERSATIONS_CONTAINER'
[Environment]::SetEnvironmentVariable("CAIG_CONVERSATIONS_CONTAINER", "conversations", "User")

echo 'setting CAIG_DEFINED_AUTH_USERS'
[Environment]::SetEnvironmentVariable("CAIG_DEFINED_AUTH_USERS", "guest:secret", "User")

echo 'setting CAIG_DOCUMENTS_CONTAINER'
[Environment]::SetEnvironmentVariable("CAIG_DOCUMENTS_CONTAINER", "documents", "User")

echo 'setting CAIG_GRAPH_SERVICE_NAME'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SERVICE_NAME", "caig-graph", "User")

echo 'setting CAIG_GRAPH_SERVICE_PORT'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SERVICE_PORT", "8001", "User")

echo 'setting CAIG_GRAPH_SERVICE_URL'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SERVICE_URL", "http://graph_service", "User")

echo 'setting CAIG_GRAPH_SOURCE_CONTAINER'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_CONTAINER", "libraries", "User")

echo 'setting CAIG_GRAPH_SOURCE_DB'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_DB", "graph", "User")

echo 'setting CAIG_GRAPH_SOURCE_OWL_FILENAME'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_OWL_FILENAME", "ontologies/libraries.owl", "User")

echo 'setting CAIG_GRAPH_SOURCE_RDF_FILENAME'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_RDF_FILENAME", "rdf/libraries-graph.nt", "User")

echo 'setting CAIG_GRAPH_SOURCE_TYPE'
[Environment]::SetEnvironmentVariable("CAIG_GRAPH_SOURCE_TYPE", "cosmos_vcore", "User")

echo 'setting CAIG_HOME'
[Environment]::SetEnvironmentVariable("CAIG_HOME", "", "User")

echo 'setting CAIG_LA_WORKSPACE_NAME'
[Environment]::SetEnvironmentVariable("CAIG_LA_WORKSPACE_NAME", "caig", "User")

echo 'setting CAIG_LOG_LEVEL'
[Environment]::SetEnvironmentVariable("CAIG_LOG_LEVEL", "info", "User")

echo 'setting CAIG_USE_ALT_SPARQL_CONSOLE'
[Environment]::SetEnvironmentVariable("CAIG_USE_ALT_SPARQL_CONSOLE", "", "User")

echo 'setting CAIG_WEB_APP_NAME'
[Environment]::SetEnvironmentVariable("CAIG_WEB_APP_NAME", "caig-web", "User")

echo 'setting CAIG_WEB_APP_PORT'
[Environment]::SetEnvironmentVariable("CAIG_WEB_APP_PORT", "8000", "User")

echo 'setting CAIG_WEB_APP_URL'
[Environment]::SetEnvironmentVariable("CAIG_WEB_APP_URL", "http://127.0.0.1", "User")

